

cc_library(
    name = "algorithm",
    srcs = ["algorithm.cc"],
    hdrs = ["algorithm.h"],
    deps = ["//graph:graph",
	    "//node:node",
	    "//nodeid:nodeid",
           ],
    visibility = ["//visibility:public"],
)

