cc_library(
    name = "algorithm",
    srcs = ["algorithm.cc"],
    hdrs = ["algorithm.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//graph",
        "//node",
        "//nodeid",
    ],
)
